CC = gcc
LD = gcc 
NASM = nasm

### Include and lib stuff ####
STDINCLUDE = /usr/include -I.
STDLIB     = /usr/lib 
SDLINCLUDE = /usr/local/include/SDL
SDLLIB	   = /usr/local/lib

CFLAGS = -g -O1 -DUNIX -DTARGET_UNIX -DGCC -DUSES_16BIT_ONLY -D__SDL__ -fomit-frame-pointer -march=pentium \
         -mpentium -finline-functions -fexpensive-optimizations -funroll-loops -funroll-all-loops -pipe \
         -fschedule-insns2 -fstrength-reduce -malign-double -mfancy-math-387 -ffast-math -fforce-addr \
         -fforce-mem `sdl-config --cflags` \
         -L$(STDLIB) -L$(SDLLIB) -I$(STDINCLUDE) -I$(SDLINCLUDE)

LDFLAGS = $(CFLAGS)

TARGET = cygne

OBJ = sdl/ddrawsdl.o sdl/filessdl.o sdl/mainsdl.o sdl/getparamsdl.o \
      gfx.o nec.o tcache.o memory.o \
      zlib/unzip.o

LIBS = `sdl-config --libs` -lz -lstdc++

all: $(TARGET)

INCS = -I. `sdl-config --cflags`

THECC = $(CC) $(CFLAGS) $(INCS)

%.o: %.asm
	$(NASM) -f elf -o $@ $<

%.o: %.c
	$(THECC) -c $< -o $@

%.o: %.cpp
	$(THECC) -c $< -o $@

cygne: $(OBJ) Makefile
	$(LD) $(LDFLAGS) -o $@ $(OBJ) $(LIBS)
	 
clean:
	rm -f cygne *.o sdl/*.o zlib/*.o
