CC = gcc
LD = gcc 
NASM = nasm

### Include and lib stuff ####
STDINCLUDE = /gcc-2.95.2/include -I.
STDLIB     = /gcc-2.95.2/lib 
SDLINCLUDE = /gcc-2.95.2/i386-mingw32msvc/include/SDL
SDLLIB	   = /gcc-2.95.2/i386-mingw32msvc/lib

CFLAGS = -O1 -DWIN32 -DTARGET_WIN32 -DGCC -DUSES_16BIT_ONLY -D__SDL__ -fomit-frame-pointer -march=pentium \
         -mpentium -finline-functions -fexpensive-optimizations -funroll-loops -funroll-all-loops -pipe \
         -fschedule-insns2 -fstrength-reduce -malign-double -mfancy-math-387 -ffast-math -mwide-multiply -fforce-addr \
         -fforce-mem `sdl-config --cflags` \
         -L$(STDLIB) -L$(SDLLIB) -I$(STDINCLUDE) -I$(SDLINCLUDE)

LDFLAGS = $(CFLAGS)

TARGET = cygne

OBJ = sdl/ddrawsdl.o sdl/filessdl.o sdl/mainsdl.o \
      gfx.o nec.o tcache.o memory.o \
      zlib/unzip.o

LIBS = `sdl-config --libs` -lz

all: $(TARGET)

INCS = -I. `sdl-config --cflags`

THECC = $(CC) $(CFLAGS) $(INCS)

%.o: %.asm
	$(NASM) -f coff -o $@ $<

%.o: %.c
	$(THECC) -c $< -o $@

%.o: %.cpp
	$(THECC) -c $< -o $@

cygne: $(OBJ) Makefile
	$(LD) $(LDFLAGS) -o $@ $(OBJ) $(LIBS)
	 
clean:
	rm -f cygne.exe *.o sdl/*.o zlib/*.o
